format = """
[  ](bg:ow_orange fg:#e0e0ce)\
[](fg:ow_orange)\
[](fg:ow_blue)\
$directory\
[](fg:ow_blue)\

$git_branch\
$git_status\

\n$character"""

palette = 'ow'

[palettes.ow]
ow_orange='#ff7d25'
ow_blue='#174e7d'

[fill]
symbol = ' ' 

[directory]
style = "fg:#e3e5e5 bg:ow_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Uni" = " "
dotfiles = ""

[git_branch]
symbol = ""
style = "bg:ow_blue"
format = """
[](fg:ow_blue)\
[](fg:ow_blue bg:ow_blue)\
[[$symbol $branch ](fg:#769ff0 bg:ow_blue)]($style)"""

[git_status]
style = "bg:ow_blue"
format = """
[[($all_status$ahead_behind )](fg:#769ff0 bg:ow_blue)]($style)\
[](fg:ow_blue)"""