format = """
[  ](bg:#ff7d25 fg:#090c0c)\
[](bg:#174e7d fg:#ff7d25)\
$directory\
[](fg:#174e7d bg:#123e64)\
$git_branch\
$git_status\
[](fg:#123e64) \
"""

[directory]
style = "fg:#e3e5e5 bg:#174e7d"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#123e64)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#123e64)]($style)'
